Fix clang-362823 make step
During execution via `check_smoke_fails` only 1/3 compile steps was
attempted, this was due to an ordering issue.

Note, this test still (expectedly) fails:
`lld: error: duplicate symbol`